package com.internportal.util;

import com.internportal.model.DocumentSource;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.draw.LineSeparator;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

/**
 * Builds the offer letter and the completion certificate with iText.
 * Only the standard PDF fonts are used, so text is plain English letters
 * (names with letters outside that set, for example Hindi, are not drawn by these fonts).
 */
public final class PdfGenerator {

    /** Printed at the bottom of every document. Change or remove it if the documents are used for real. */
    public static final String FOOTER_NOTE = "Computer-generated by the Internship Management Portal "
            + "(academic project). It is not an official document of the company.";

    private static final BaseColor PRIMARY = new BaseColor(30, 90, 168);
    private static final BaseColor GRAY = new BaseColor(110, 110, 110);
    private static final BaseColor LIGHT = new BaseColor(200, 205, 215);
    private static final BaseColor PANEL = new BaseColor(245, 247, 250);
    private static final DateTimeFormatter DATE = DateTimeFormatter.ofPattern("dd MMM yyyy", Locale.ENGLISH);

    private PdfGenerator() { }

    // ---------------------------------------------------------------- Offer letter

    public static void offerLetter(DocumentSource s, String referenceNo, LocalDate issuedOn, Path target)
            throws IOException {
        Font titleFont = font(FontFactory.HELVETICA_BOLD, 20, PRIMARY);
        Font smallFont = font(FontFactory.HELVETICA, 9, GRAY);
        Font noteFont = font(FontFactory.HELVETICA_OBLIQUE, 8, GRAY);
        Font body = font(FontFactory.HELVETICA, 11, BaseColor.BLACK);
        Font bold = font(FontFactory.HELVETICA_BOLD, 11, BaseColor.BLACK);

        Document doc = new Document(PageSize.A4, 56, 56, 48, 48);
        try (OutputStream out = Files.newOutputStream(target)) {
            PdfWriter.getInstance(doc, out);
            doc.addTitle("Offer Letter " + referenceNo);
            doc.addAuthor("Internship Management Portal");
            doc.open();

            // Header
            doc.add(centered(s.getCompanyName(), titleFont, 2));
            String about = join(" | ", s.getIndustry(), s.getWebsite());
            if (!about.isEmpty()) {
                doc.add(centered(about, smallFont, 6));
            }
            doc.add(new Chunk(new LineSeparator(1.2f, 100f, PRIMARY, Element.ALIGN_CENTER, -2f)));
            doc.add(spacer(10));

            // Reference and date
            PdfPTable meta = new PdfPTable(2);
            meta.setWidthPercentage(100);
            meta.addCell(plainCell("Ref: " + referenceNo, body, Element.ALIGN_LEFT));
            meta.addCell(plainCell("Date: " + issuedOn.format(DATE), body, Element.ALIGN_RIGHT));
            doc.add(meta);

            // Addressee
            Paragraph to = new Paragraph();
            to.setSpacingBefore(14);
            to.add(new Chunk("To,\n", body));
            to.add(new Chunk(s.getStudentName() + "\n", bold));
            to.add(new Chunk(s.getStudentEmail(), body));
            if (s.getCourse() != null && !s.getCourse().trim().isEmpty()) {
                to.add(new Chunk("\n" + s.getCourse(), body));
            }
            doc.add(to);

            // Subject
            Paragraph subject = new Paragraph();
            subject.setSpacingBefore(14);
            subject.add(new Chunk("Subject: Offer of internship - " + s.getInternshipTitle(), bold));
            doc.add(subject);

            // Greeting and introduction
            Paragraph hello = new Paragraph("Dear " + firstName(s.getStudentName()) + ",", body);
            hello.setSpacingBefore(14);
            hello.setSpacingAfter(8);
            doc.add(hello);

            Paragraph intro = new Paragraph("We are pleased to inform you that you have been selected for the "
                    + "position of " + s.getInternshipTitle() + " at " + s.getCompanyName()
                    + ", through the Internship Management Portal. The details of your internship are "
                    + "given below.", body);
            intro.setLeading(16);
            intro.setAlignment(Element.ALIGN_JUSTIFIED);
            intro.setSpacingAfter(10);
            doc.add(intro);

            // Details table
            PdfPTable details = new PdfPTable(new float[]{1f, 2f});
            details.setWidthPercentage(100);
            addDetailRow(details, "Position", s.getInternshipTitle(), bold, body);
            addDetailRow(details, "Company", s.getCompanyName(), bold, body);
            addDetailRow(details, "Duration", s.getDurationWeeks() + " weeks", bold, body);
            addDetailRow(details, "Start date", s.getStartDate().format(DATE), bold, body);
            addDetailRow(details, "End date (last day)", s.getEndDate().format(DATE), bold, body);
            addDetailRow(details, "Stipend",
                    String.format(Locale.ENGLISH, "INR %,.0f per month", s.getStipend()), bold, body);
            doc.add(details);

            // Terms
            Paragraph termsHeading = new Paragraph("Terms", bold);
            termsHeading.setSpacingBefore(14);
            termsHeading.setSpacingAfter(4);
            doc.add(termsHeading);
            doc.add(termLine("- You will keep a weekly logbook for every week of the internship. "
                    + "Each entry is reviewed and graded.", body));
            doc.add(termLine("- A completion certificate is issued after every week has been submitted "
                    + "and graded.", body));

            // Closing
            Paragraph closing = new Paragraph("We wish you a rewarding internship experience.", body);
            closing.setSpacingBefore(12);
            doc.add(closing);

            Paragraph sign = new Paragraph();
            sign.setSpacingBefore(24);
            sign.add(new Chunk("Yours sincerely,\n\n\n", body));
            sign.add(new Chunk("Internship Coordinator\n", bold));
            sign.add(new Chunk("Internship Management Portal\non behalf of " + s.getCompanyName(), body));
            doc.add(sign);

            Paragraph note = new Paragraph(FOOTER_NOTE, noteFont);
            note.setSpacingBefore(24);
            note.setAlignment(Element.ALIGN_CENTER);
            doc.add(note);

            doc.close();
        } catch (DocumentException e) {
            throw new IOException("PDF error: " + e.getMessage(), e);
        }
    }

    // ---------------------------------------------------------------- Completion certificate

    public static void certificate(DocumentSource s, String referenceNo, LocalDate issuedOn, Path target)
            throws IOException {
        Font heading = font(FontFactory.TIMES_BOLD, 40, PRIMARY);
        Font subHeading = font(FontFactory.TIMES_ROMAN, 20, GRAY);
        Font italic = font(FontFactory.TIMES_ITALIC, 14, GRAY);
        Font nameFont = font(FontFactory.TIMES_BOLD, 32, BaseColor.BLACK);
        Font body = font(FontFactory.TIMES_ROMAN, 15, BaseColor.BLACK);
        Font bodyBold = font(FontFactory.TIMES_BOLD, 15, BaseColor.BLACK);
        Font small = font(FontFactory.TIMES_ROMAN, 11, GRAY);
        Font noteFont = font(FontFactory.HELVETICA_OBLIQUE, 8, GRAY);

        Document doc = new Document(PageSize.A4.rotate(), 70, 70, 60, 50);
        try (OutputStream out = Files.newOutputStream(target)) {
            PdfWriter writer = PdfWriter.getInstance(doc, out);
            doc.addTitle("Completion Certificate " + referenceNo);
            doc.addAuthor("Internship Management Portal");
            doc.open();

            // Double border
            Rectangle page = doc.getPageSize();
            PdfContentByte canvas = writer.getDirectContentUnder();
            canvas.setColorStroke(PRIMARY);
            canvas.setLineWidth(4f);
            canvas.rectangle(24, 24, page.getWidth() - 48, page.getHeight() - 48);
            canvas.stroke();
            canvas.setLineWidth(1f);
            canvas.rectangle(34, 34, page.getWidth() - 68, page.getHeight() - 68);
            canvas.stroke();

            doc.add(centered("CERTIFICATE", heading, 0));
            doc.add(centered("OF COMPLETION", subHeading, 18));
            doc.add(centered("This is to certify that", italic, 6));
            doc.add(centered(s.getStudentName(), nameFont, 0));
            doc.add(new Chunk(new LineSeparator(0.8f, 50f, GRAY, Element.ALIGN_CENTER, -4f)));
            doc.add(spacer(14));

            Paragraph statement = new Paragraph();
            statement.setAlignment(Element.ALIGN_CENTER);
            statement.setLeading(24);
            statement.add(new Chunk("has successfully completed the " + s.getDurationWeeks()
                    + "-week internship as ", body));
            statement.add(new Chunk(s.getInternshipTitle(), bodyBold));
            statement.add(new Chunk(" at ", body));
            statement.add(new Chunk(s.getCompanyName(), bodyBold));
            statement.add(new Chunk(", from " + s.getStartDate().format(DATE)
                    + " to " + s.getEndDate().format(DATE) + ".", body));
            doc.add(statement);

            if (s.getAverageGrade() != null) {
                Paragraph performance = new Paragraph(String.format(Locale.ENGLISH,
                        "Logbook performance: %.1f / 10 across %d graded weeks.",
                        s.getAverageGrade(), s.getGradedWeeks()), body);
                performance.setAlignment(Element.ALIGN_CENTER);
                performance.setSpacingBefore(12);
                doc.add(performance);
            }

            // Date and signature
            PdfPTable signatures = new PdfPTable(2);
            signatures.setWidthPercentage(70);
            signatures.setSpacingBefore(34);
            signatures.addCell(signatureCell(issuedOn.format(DATE), "Date of issue", body, small));
            signatures.addCell(signatureCell("", "Internship Coordinator", body, small));
            doc.add(signatures);

            Paragraph reference = new Paragraph("Certificate reference: " + referenceNo, small);
            reference.setAlignment(Element.ALIGN_CENTER);
            reference.setSpacingBefore(16);
            doc.add(reference);

            Paragraph note = new Paragraph(FOOTER_NOTE, noteFont);
            note.setAlignment(Element.ALIGN_CENTER);
            note.setSpacingBefore(6);
            doc.add(note);

            doc.close();
        } catch (DocumentException e) {
            throw new IOException("PDF error: " + e.getMessage(), e);
        }
    }

    // ---------------------------------------------------------------- Helpers

    private static Font font(String name, float size, BaseColor color) {
        return FontFactory.getFont(name, size, color);
    }

    private static Paragraph centered(String text, Font font, float spaceAfter) {
        Paragraph p = new Paragraph(text, font);
        p.setAlignment(Element.ALIGN_CENTER);
        p.setSpacingAfter(spaceAfter);
        return p;
    }

    private static Paragraph spacer(float height) {
        Paragraph p = new Paragraph(" ");
        p.setLeading(height);
        return p;
    }

    private static Paragraph termLine(String text, Font font) {
        Paragraph p = new Paragraph(text, font);
        p.setLeading(15);
        p.setSpacingAfter(3);
        return p;
    }

    private static PdfPCell plainCell(String text, Font font, int alignment) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setBorder(Rectangle.NO_BORDER);
        cell.setHorizontalAlignment(alignment);
        cell.setPaddingLeft(0);
        cell.setPaddingRight(0);
        return cell;
    }

    private static void addDetailRow(PdfPTable table, String label, String value, Font labelFont, Font valueFont) {
        PdfPCell left = new PdfPCell(new Phrase(label, labelFont));
        left.setBackgroundColor(PANEL);
        left.setBorderColor(LIGHT);
        left.setPadding(5);
        table.addCell(left);

        PdfPCell right = new PdfPCell(new Phrase(value, valueFont));
        right.setBorderColor(LIGHT);
        right.setPadding(5);
        table.addCell(right);
    }

    private static PdfPCell signatureCell(String above, String label, Font body, Font small) {
        Paragraph p = new Paragraph();
        p.setAlignment(Element.ALIGN_CENTER);
        p.add(new Chunk(above + "\n", body));
        p.add(new Chunk("______________________\n", body));
        p.add(new Chunk(label, small));

        PdfPCell cell = new PdfPCell();
        cell.setBorder(Rectangle.NO_BORDER);
        cell.addElement(p);
        return cell;
    }

    private static String firstName(String fullName) {
        return fullName.trim().split("\\s+")[0];
    }

    private static String join(String separator, String... parts) {
        StringBuilder sb = new StringBuilder();
        for (String part : parts) {
            if (part != null && !part.trim().isEmpty()) {
                if (sb.length() > 0) {
                    sb.append(separator);
                }
                sb.append(part.trim());
            }
        }
        return sb.toString();
    }
}
